### ISSUE TITLE
Estimators

### ISSUE THREAD

**Issue by vincecr0ft** [Histimator/Histimator#1]
Add various estimators for normalisations of samples and number of events etc.

**Comment by yhaddad** [comment]
Implementing a binned likelihood estimator as it is done in `profit` but takes `histomator.models` instead

**Comment by yhaddad** [comment]
`BinnedLH` estimator is now available and can be called by `from histimator import BinnedLH`. Please refer to  #5 for more details.

**Comment by vincecr0ft** [comment]
binnedLH 
 - [x] run with multiple parameters - model.pdf(bin_i, poi1, poi2)
 - [x] identify parameters  - binnedLH(model, pois, nps)
 - [x] modify Likelihood for constraints

**Comment by vincecr0ft** [comment]
Need to really confirm that the likelihood for models with constrained terms is correct.

**Comment by yhaddad** [comment]
I am closing this issue as it is currently implemented
