### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by vincecr0ft** [Histimator/Histimator#17]
Setup CI and compilation with Jenkins before uploading to pypy. 

Clean up directory and update documentation.

**Comment by yhaddad** [comment]
This is related to #18 as well

**Comment by yhaddad** [comment]
TravisCL compilation is already implemented in this package. I have activated the automatic build when a PR is pushed and when the master is changed. See #22

**Comment by yhaddad** [comment]
Continuous Integration is now implemented,  this issue can then be considered closed.
